@startuml
digraph G {
    node [shape=box];
    compound=true;
    splines=ortho;
    subgraph cluster1 {
        color=blue;
        node [color=blue];
        subgraph cluster11 {
            label="PHP 7.x/8.x"
            sapnwrfc7 [label="G. Kraliks sapnwrfc"];
        }
        subgraph cluster12 {
            label="PHP 5.x"
            sapnwrfc5 [label="P. Hardings sapnwrfc"];
            saprfc [label="E. Kouckys saprfc"];
        }
    }
    subgraph cluster2 {
        color=green;
        node [color=green];
        label="php-sap/interfaces"
        subgraph cluster21 {
            label="php-sap/common"
            "php-sap/saprfc-koucky" -> saprfc [color=green];
            "php-sap/saprfc-harding" -> sapnwrfc5 [color=green];
            "php-sap/saprfc-kralik" -> sapnwrfc7 [color=green];
        }
    }
    subgraph cluster3 {
        color=red;
        node [color=red];
        label="your code";
        yourcode [label="create() ➔ setConfiguration() ➔ invoke()"];
    }
    yourcode -> "php-sap/saprfc-harding" [lhead=cluster2 color=red];
}
@enduml
